// Generated by js_of_ocaml 2.4
(function(m){"use strict";var
w=255,v='"',c="",n=" : file already exists",u="/",t="fd ";function
G(){var
b=m.console?m.console:{},c=["log","debug","info","warn","error","assert","dir","dirxml","trace","group","groupCollapsed","groupEnd","time","timeEnd"];function
d(){}for(var
a=0;a<c.length;a++)if(!b[c[a]])b[c[a]]=d;return b}function
z(a,b){throw[0,a,b]}function
q(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=m.console;b&&b.error&&b.error(a)}var
f=[0];function
p(a,b){if(!a)return c;if(a&1)return p(a-1,b)+b;var
d=p(a>>1,b);return d+d}function
g(a){if(a!=null){this.bytes=this.fullBytes=a;this.last=this.len=a.length}}function
B(){z(f[4],new
g("index out of bounds"))}g.prototype={string:null,bytes:null,fullBytes:null,array:null,len:null,last:0,toJsString:function(){var
a=this.getFullBytes();try{return this.string=decodeURIComponent(escape(a))}catch(e){q('MlString.toJsString: wrong encoding for "'+a+v);return a}},toBytes:function(){if(this.string!=null)try{var
a=unescape(encodeURIComponent(this.string))}catch(e){q('MlString.toBytes: wrong encoding for "'+this.string+v);var
a=this.string}else{var
a=c,d=this.array,f=d.length;for(var
b=0;b<f;b++)a+=String.fromCharCode(d[b])}this.bytes=this.fullBytes=a;this.last=this.len=a.length;return a},getBytes:function(){var
a=this.bytes;if(a==null)a=this.toBytes();return a},getFullBytes:function(){var
a=this.fullBytes;if(a!==null)return a;a=this.bytes;if(a==null)a=this.toBytes();if(this.last<this.len){this.bytes=a+=p(this.len-this.last,"\0");this.last=this.len}this.fullBytes=a;return a},toArray:function(){var
c=this.bytes;if(c==null)c=this.toBytes();var
b=[],d=this.last;for(var
a=0;a<d;a++)b[a]=c.charCodeAt(a);for(d=this.len;a<d;a++)b[a]=0;this.string=this.bytes=this.fullBytes=null;this.last=this.len;this.array=b;return b},getArray:function(){var
a=this.array;if(!a)a=this.toArray();return a},getLen:function(){var
a=this.len;if(a!==null)return a;this.toBytes();return this.len},toString:function(){var
a=this.string;return a?a:this.toJsString()},valueOf:function(){var
a=this.string;return a?a:this.toJsString()},blitToArray:function(a,b,c,d){var
g=this.array;if(g)if(c<=a)for(var
f=0;f<d;f++)b[c+f]=g[a+f];else
for(var
f=d-1;f>=0;f--)b[c+f]=g[a+f];else{var
e=this.bytes;if(e==null)e=this.toBytes();var
h=this.last-a;if(d<=h)for(var
f=0;f<d;f++)b[c+f]=e.charCodeAt(a+f);else{for(var
f=0;f<h;f++)b[c+f]=e.charCodeAt(a+f);for(;f<d;f++)b[c+f]=0}}},get:function(a){var
c=this.array;if(c)return c[a];var
b=this.bytes;if(b==null)b=this.toBytes();return a<this.last?b.charCodeAt(a):0},safeGet:function(a){if(this.len==null)this.toBytes();if(a<0||a>=this.len)B();return this.get(a)},set:function(a,b){var
c=this.array;if(!c){if(this.last==a){this.bytes+=String.fromCharCode(b&w);this.last++;return 0}c=this.toArray()}else
if(this.bytes!=null)this.bytes=this.fullBytes=this.string=null;c[a]=b&w;return 0},safeSet:function(a,b){if(this.len==null)this.toBytes();if(a<0||a>=this.len)B();this.set(a,b)},fill:function(a,b,c){if(a>=this.last&&this.last&&c==0)return;var
d=this.array;if(!d)d=this.toArray();else
if(this.bytes!=null)this.bytes=this.fullBytes=this.string=null;var
e=a+b;for(var
f=a;f<e;f++)d[f]=c},compare:function(a){if(this.string!=null&&a.string!=null){if(this.string<a.string)return-1;if(this.string>a.string)return 1;return 0}var
b=this.getFullBytes(),c=a.getFullBytes();if(b<c)return-1;if(b>c)return 1;return 0},equal:function(a){if(this.string!=null&&a.string!=null)return this.string==a.string;return this.getFullBytes()==a.getFullBytes()},lessThan:function(a){if(this.string!=null&&a.string!=null)return this.string<a.string;return this.getFullBytes()<a.getFullBytes()},lessEqual:function(a){if(this.string!=null&&a.string!=null)return this.string<=a.string;return this.getFullBytes()<=a.getFullBytes()}};function
x(a){this.string=a}x.prototype=new
g();function
A(a,b){z(a,new
x(b))}function
e(a){A(f[2],a)}function
H(a){if(!a.opened)e("Cannot flush a closed channel");if(a.buffer==c)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=c;return 0}function
y(a){a=a
instanceof
g?a.toString():a;e(a+": No such file or directory")}var
D=u;function
k(a){a=a
instanceof
g?a.toString():a;if(a.charCodeAt(0)!=47)a=D+a;var
f=a.split(u),b=[];for(var
d=0;d<f.length;d++)switch(f[d]){case"..":if(b.length>1)b.pop();break;case".":break;case
c:if(b.length==0)b.push(c);break;default:b.push(f[d]);break}b.orig=a;return b}function
h(){this.content={}}h.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
l=new
h();l.mk(c,new
h());function
o(a){var
b=l;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))y(a.orig);b=b.get(a[c])}return b}function
R(a){var
c=k(a),b=o(c);return b
instanceof
h?1:0}function
F(a){A(f[4],a)}function
i(a){this.data=a}i.prototype={content:function(){return this.data},truncate:function(){this.data.length=0}};function
E(a,b){var
f=k(a),c=l;for(var
j=0;j<f.length-1;j++){var
d=f[j];if(!c.exists(d))c.mk(d,new
h());c=c.get(d);if(!(c
instanceof
h))e(f.orig+n)}var
d=f[f.length-1];if(c.exists(d))e(f.orig+n);if(b
instanceof
h)c.mk(d,b);else
if(b
instanceof
i)c.mk(d,b);else
if(b
instanceof
g)c.mk(d,new
i(b.getArray()));else
if(b
instanceof
Array)c.mk(d,new
i(b));else
if(b.toString)c.mk(d,new
i(new
g(b.toString()).getArray()));else
F("caml_fs_register");return 0}function
Q(a){var
b=l,d=k(a),f,e;for(var
c=0;c<d.length;c++){if(b.auto){f=b.auto;e=c}if(!(b.exists&&b.exists(d[c])))return f?f(d,e):0;b=b.get(d[c])}return 1}function
j(a,b,c){if(f.fds===undefined)f.fds=new
Array();c=c?c:{};var
d={};d.array=b;d.offset=c.append?d.array.length:0;d.flags=c;f.fds[a]=d;f.fd_last_idx=a;return a}function
T(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),l=k(a);if(d.rdonly&&d.wronly)e(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)e(h+" : flags Open_text and Open_binary are not compatible");if(Q(a)){if(R(a))e(h+" : is a directory");if(d.create&&d.excl)e(h+n);var
i=f.fd_last_idx?f.fd_last_idx:0,g=o(l);if(d.truncate)g.truncate();return j(i+1,g.content(),d)}else
if(d.create){var
i=f.fd_last_idx?f.fd_last_idx:0;E(a,[]);var
g=o(l);return j(i+1,g.content(),d)}else
y(a)}j(0,[]);j(1,[]);j(2,[]);function
I(a){var
b=f.fds[a];if(b.flags.wronly)e(t+a+" is writeonly");return{data:b,fd:a,opened:true}}function
S(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=m.console;b&&b.log&&b.log(a)}var
d=new
Array();function
P(a,b){var
f=new
g(b),d=f.getLen();for(var
c=0;c<d;c++)a.data.array[a.data.offset+c]=f.get(c);a.data.offset+=d;return 0}function
J(a){var
b;switch(a){case
1:b=S;break;case
2:b=q;break;default:b=P}var
h=f.fds[a];if(h.flags.rdonly)e(t+a+" is readonly");var
g={data:h,fd:a,opened:true,buffer:c,output:b};d[g.fd]=g;return g}function
K(){var
a=0;for(var
b
in
d)if(d[b].opened)a=[0,d[b],a];return a}function
M(a){return new
g(a)}function
N(a,b){f[a+1]=b}var
L={};function
O(a,b){L[a.toString()]=b;return 0}var
s=J,a=M,b=N;b(11,[0,a("Undefined_recursive_module")]);b(10,[0,a("Assert_failure")]);b(9,[0,a("Sys_blocked_io")]);b(8,[0,a("Stack_overflow")]);b(7,[0,a("Match_failure")]);b(6,[0,a("Not_found")]);b(5,[0,a("Division_by_zero")]);b(4,[0,a("End_of_file")]);b(3,[0,a("Invalid_argument")]);b(2,[0,a("Failure")]);b(1,[0,a("Sys_error")]);b(0,[0,a("Out_of_memory")]);I(0);s(1);s(2);var
C=a("Pervasives.do_at_exit");function
r(a){var
b=K(0);for(;;){if(b){var
c=b[2],d=b[1];try{H(d)}catch(e){}var
b=c;continue}return 0}}O(C,r);G(0).log("hello world");r(0);return}(function(){return this}()));
