// Generated by js_of_ocaml 2.4
(function(i){"use strict";var
ay=254,ar=".",L=255,ax='"',aw=250,av="jsError",au=512,h="",K=" : file already exists",aq="/",at="fd ",as=">",J="number";function
aF(a,b){throw[0,a,b]}function
Q(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=i.console;b&&b.error&&b.error(a)}var
e=[0];function
P(a,b){if(!a)return h;if(a&1)return P(a-1,b)+b;var
c=P(a>>1,b);return c+c}function
d(a){if(a!=null){this.bytes=this.fullBytes=a;this.last=this.len=a.length}}function
aH(){aF(e[4],new
d("index out of bounds"))}d.prototype={string:null,bytes:null,fullBytes:null,array:null,len:null,last:0,toJsString:function(){var
a=this.getFullBytes();try{return this.string=decodeURIComponent(escape(a))}catch(f){Q('MlString.toJsString: wrong encoding for "'+a+ax);return a}},toBytes:function(){if(this.string!=null)try{var
a=unescape(encodeURIComponent(this.string))}catch(f){Q('MlString.toBytes: wrong encoding for "'+this.string+ax);var
a=this.string}else{var
a=h,c=this.array,d=c.length;for(var
b=0;b<d;b++)a+=String.fromCharCode(c[b])}this.bytes=this.fullBytes=a;this.last=this.len=a.length;return a},getBytes:function(){var
a=this.bytes;if(a==null)a=this.toBytes();return a},getFullBytes:function(){var
a=this.fullBytes;if(a!==null)return a;a=this.bytes;if(a==null)a=this.toBytes();if(this.last<this.len){this.bytes=a+=P(this.len-this.last,"\0");this.last=this.len}this.fullBytes=a;return a},toArray:function(){var
c=this.bytes;if(c==null)c=this.toBytes();var
b=[],d=this.last;for(var
a=0;a<d;a++)b[a]=c.charCodeAt(a);for(d=this.len;a<d;a++)b[a]=0;this.string=this.bytes=this.fullBytes=null;this.last=this.len;this.array=b;return b},getArray:function(){var
a=this.array;if(!a)a=this.toArray();return a},getLen:function(){var
a=this.len;if(a!==null)return a;this.toBytes();return this.len},toString:function(){var
a=this.string;return a?a:this.toJsString()},valueOf:function(){var
a=this.string;return a?a:this.toJsString()},blitToArray:function(a,b,c,d){var
g=this.array;if(g)if(c<=a)for(var
e=0;e<d;e++)b[c+e]=g[a+e];else
for(var
e=d-1;e>=0;e--)b[c+e]=g[a+e];else{var
f=this.bytes;if(f==null)f=this.toBytes();var
h=this.last-a;if(d<=h)for(var
e=0;e<d;e++)b[c+e]=f.charCodeAt(a+e);else{for(var
e=0;e<h;e++)b[c+e]=f.charCodeAt(a+e);for(;e<d;e++)b[c+e]=0}}},get:function(a){var
c=this.array;if(c)return c[a];var
b=this.bytes;if(b==null)b=this.toBytes();return a<this.last?b.charCodeAt(a):0},safeGet:function(a){if(this.len==null)this.toBytes();if(a<0||a>=this.len)aH();return this.get(a)},set:function(a,b){var
c=this.array;if(!c){if(this.last==a){this.bytes+=String.fromCharCode(b&L);this.last++;return 0}c=this.toArray()}else
if(this.bytes!=null)this.bytes=this.fullBytes=this.string=null;c[a]=b&L;return 0},safeSet:function(a,b){if(this.len==null)this.toBytes();if(a<0||a>=this.len)aH();this.set(a,b)},fill:function(a,b,c){if(a>=this.last&&this.last&&c==0)return;var
d=this.array;if(!d)d=this.toArray();else
if(this.bytes!=null)this.bytes=this.fullBytes=this.string=null;var
f=a+b;for(var
e=a;e<f;e++)d[e]=c},compare:function(a){if(this.string!=null&&a.string!=null){if(this.string<a.string)return-1;if(this.string>a.string)return 1;return 0}var
b=this.getFullBytes(),c=a.getFullBytes();if(b<c)return-1;if(b>c)return 1;return 0},equal:function(a){if(this.string!=null&&a.string!=null)return this.string==a.string;return this.getFullBytes()==a.getFullBytes()},lessThan:function(a){if(this.string!=null&&a.string!=null)return this.string<a.string;return this.getFullBytes()<a.getFullBytes()},lessEqual:function(a){if(this.string!=null&&a.string!=null)return this.string<=a.string;return this.getFullBytes()<=a.getFullBytes()}};function
q(a){this.string=a}q.prototype=new
d();function
aA(a,b,c,d,e){if(e===0)return 0;if(a.array!=null&&c.last==0&&d==0&&e==c.len){c.array=a.array.slice(b,b+e);c.bytes=c.string=null;return 0}if(d===c.last&&c.bytes!=null){var
f=a.bytes;if(f==null)f=a.toBytes();if(b>0||a.last>e)f=f.slice(b,b+e);c.bytes+=f;c.last+=f.length;return 0}var
g=c.array;if(!g)g=c.toArray();else
c.bytes=c.string=null;a.blitToArray(b,g,d,e);return 0}function
n(c,b){if(c.fun)return n(c.fun,b);var
a=c.length,d=a-b.length;if(d==0)return c.apply(null,b);else
if(d<0)return n(c.apply(null,b.slice(0,a)),b.slice(a));else
return function(a){return n(c,b.concat([a]))}}function
az(a){this.bytes=h;this.len=a}az.prototype=new
d();function
aG(a,b){aF(a,new
q(b))}function
O(a){aG(e[4],a)}function
aB(a){if(a<0)O("String.create");return new
az(a)}function
bb(a,b,c,d){a.fill(b,c,d);return 0}function
be(a,b){var
c=a[3]<<16,d=b[3]<<16;if(c>d)return 1;if(c<d)return-1;if(a[2]>b[2])return 1;if(a[2]<b[2])return-1;if(a[1]>b[1])return 1;if(a[1]<b[1])return-1;return 0}function
bf(a,b){if(a<b)return-1;if(a==b)return 0;return 1}function
M(a,b,c){var
f=[];for(;;){if(!(c&&a===b))if(a
instanceof
d)if(b
instanceof
d){if(a!==b){var
e=a.compare(b);if(e!=0)return e}}else
return 1;else
if(a
instanceof
Array&&a[0]===(a[0]|0)){var
g=a[0];if(g===ay)g=0;if(g===aw){a=a[1];continue}else
if(b
instanceof
Array&&b[0]===(b[0]|0)){var
h=b[0];if(h===ay)h=0;if(h===aw){b=b[1];continue}else
if(g!=h)return g<h?-1:1;else
switch(g){case
248:var
e=bf(a[2],b[2]);if(e!=0)return e;break;case
251:O("equal: abstract value");case
L:var
e=be(a,b);if(e!=0)return e;break;default:if(a.length!=b.length)return a.length<b.length?-1:1;if(a.length>1)f.push(a,b,1)}}else
return 1}else
if(b
instanceof
d||b
instanceof
Array&&b[0]===(b[0]|0))return-1;else
if(typeof
a!=J&&a&&a.compare)return a.compare(b,c);else{if(a<b)return-1;if(a>b)return 1;if(a!=b){if(!c)return NaN;if(a==a)return 1;if(b==b)return-1}}if(f.length==0)return 0;var
i=f.pop();b=f.pop();a=f.pop();if(i+1<a.length)f.push(a,b,i+1);a=a[i];b=b[i]}}function
bd(a,b){return+(M(a,b,false)>=0)}function
bg(){var
b=i.console?i.console:{},c=["log","debug","info","warn","error","assert","dir","dirxml","trace","group","groupCollapsed","groupEnd","time","timeEnd"];function
d(){}for(var
a=0;a<c.length;a++)if(!b[c[a]])b[c[a]]=d;return b}function
bh(a){var
c=Array.prototype.slice;return function(){var
b=arguments.length>0?c.call(arguments):[undefined];return n(a,b)}}function
bi(a,b){return+(M(a,b,false)<=0)}function
bj(a,b){return+(M(a,b,false)<0)}function
g(a){aG(e[2],a)}function
aC(a){if(!a.opened)g("Cannot flush a closed channel");if(a.buffer==h)return 0;if(a.output)switch(a.output.length){case
2:a.output(a,a.buffer);break;default:a.output(a.buffer)}a.buffer=h;return 0}function
aE(a){a=a
instanceof
d?a.toString():a;g(a+": No such file or directory")}var
ba=aq;function
x(a){a=a
instanceof
d?a.toString():a;if(a.charCodeAt(0)!=47)a=ba+a;var
e=a.split(aq),b=[];for(var
c=0;c<e.length;c++)switch(e[c]){case"..":if(b.length>1)b.pop();break;case
ar:break;case
h:if(b.length==0)b.push(h);break;default:b.push(e[c]);break}b.orig=a;return b}function
l(){this.content={}}l.prototype={exists:function(a){return this.content[a]?1:0},mk:function(a,b){this.content[a]=b},get:function(a){return this.content[a]},list:function(){var
a=[];for(var
b
in
this.content)a.push(b);return a},remove:function(a){delete
this.content[a]}};var
z=new
l();z.mk(h,new
l());function
N(a){var
b=z;for(var
c=0;c<a.length;c++){if(!(b.exists&&b.exists(a[c])))aE(a.orig);b=b.get(a[c])}return b}function
bw(a){var
c=x(a),b=N(c);return b
instanceof
l?1:0}function
p(a){this.data=a}p.prototype={content:function(){return this.data},truncate:function(){this.data.length=0}};function
bc(a,b){var
f=x(a),c=z;for(var
h=0;h<f.length-1;h++){var
e=f[h];if(!c.exists(e))c.mk(e,new
l());c=c.get(e);if(!(c
instanceof
l))g(f.orig+K)}var
e=f[f.length-1];if(c.exists(e))g(f.orig+K);if(b
instanceof
l)c.mk(e,b);else
if(b
instanceof
p)c.mk(e,b);else
if(b
instanceof
d)c.mk(e,new
p(b.getArray()));else
if(b
instanceof
Array)c.mk(e,new
p(b));else
if(b.toString)c.mk(e,new
p(new
d(b.toString()).getArray()));else
O("caml_fs_register");return 0}function
bv(a){var
b=z,d=x(a),e,f;for(var
c=0;c<d.length;c++){if(b.auto){e=b.auto;f=c}if(!(b.exists&&b.exists(d[c])))return e?e(d,f):0;b=b.get(d[c])}return 1}function
r(a,b,c){if(e.fds===undefined)e.fds=new
Array();c=c?c:{};var
d={};d.array=b;d.offset=c.append?d.array.length:0;d.flags=c;e.fds[a]=d;e.fd_last_idx=a;return a}function
bz(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}var
h=a.toString(),j=x(a);if(d.rdonly&&d.wronly)g(h+" : flags Open_rdonly and Open_wronly are not compatible");if(d.text&&d.binary)g(h+" : flags Open_text and Open_binary are not compatible");if(bv(a)){if(bw(a))g(h+" : is a directory");if(d.create&&d.excl)g(h+K);var
i=e.fd_last_idx?e.fd_last_idx:0,f=N(j);if(d.truncate)f.truncate();return r(i+1,f.content(),d)}else
if(d.create){var
i=e.fd_last_idx?e.fd_last_idx:0;bc(a,[]);var
f=N(j);return r(i+1,f.content(),d)}else
aE(a)}r(0,[]);r(1,[]);r(2,[]);function
bk(a){var
b=e.fds[a];if(b.flags.wronly)g(at+a+" is writeonly");return{data:b,fd:a,opened:true}}function
by(a){if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
b=i.console;b&&b.log&&b.log(a)}var
y=new
Array();function
bt(a,b){var
f=new
d(b),e=f.getLen();for(var
c=0;c<e;c++)a.data.array[a.data.offset+c]=f.get(c);a.data.offset+=e;return 0}function
bl(a){var
b;switch(a){case
1:b=by;break;case
2:b=Q;break;default:b=bt}var
d=e.fds[a];if(d.flags.rdonly)g(at+a+" is readonly");var
c={data:d,fd:a,opened:true,buffer:h,output:b};y[c.fd]=c;return c}function
bm(){var
a=0;for(var
b
in
y)if(y[b].opened)a=[0,y[b],a];return a}function
bn(a,b,c,d){if(!a.opened)g("Cannot output to a closed channel");var
f;if(c==0&&b.getLen()==d)f=b;else{f=aB(d);aA(b,c,f,0,d)}var
e=f.toString(),h=e.lastIndexOf("\n");if(h<0)a.buffer+=e;else{a.buffer+=e.substr(0,h+1);aC(a);a.buffer+=e.substr(h+1)}return 0}if(!Math.imul)Math.imul=function(a,b){return((a>>16)*b<<16)+(a&65535)*b|0};var
bo=Math.imul;function
bq(a){return new
d(a)}function
br(a,b){e[a+1]=b}var
aD={};function
bs(a,b){aD[a.toString()]=b;return 0}function
bu(){return 32}function
bp(a){return aD[a]}function
bx(a){if(a
instanceof
Array)return a;if(i.RangeError&&a
instanceof
i.RangeError&&a.message&&a.message.match(/maximum call stack/i))return[0,e[9]];if(i.InternalError&&a
instanceof
i.InternalError&&a.message&&a.message.match(/too much recursion/i))return[0,e[9]];if(a
instanceof
i.Error)return[0,bp(av),a];return[0,e[3],new
q(String(a))]}var
I=aA,v=aB,an=aC,am=bl,a=bq,c=br,ao=bs,ap=bx;function
k(a,b){return a.length==1?a(b):n(a,[b])}function
w(a,b,c,d){return a.length==3?a(b,c,d):n(a,[b,c,d])}var
R=[0,a("Failure")],S=[0,a("Invalid_argument")],C=[0,a("Not_found")];c(11,[0,a("Undefined_recursive_module")]);c(10,[0,a("Assert_failure")]);c(9,[0,a("Sys_blocked_io")]);c(8,[0,a("Stack_overflow")]);c(7,[0,a("Match_failure")]);c(6,C);c(5,[0,a("Division_by_zero")]);c(4,[0,a("End_of_file")]);c(3,S);c(2,R);c(1,[0,a("Sys_error")]);c(0,[0,a("Out_of_memory")]);var
aL=a("output"),aN=a("Pervasives.do_at_exit"),aO=a("String.blit"),aQ=a("Buffer.add_substring"),aP=a("Buffer.add: cannot grow buffer"),a2=[3,0,3],a3=a(ar),aY=a(as),aZ=a("</"),aV=a(as),aW=a("<"),aT=a("\n"),aR=a("Format.Empty_queue"),aS=[0,a(h)],a7=a("Js.Error"),a8=a(av);function
A(a){throw[0,S,a]}var
aI=-2147483648-1|0;function
s(a,b){var
c=a.getLen(),e=b.getLen(),d=v(c+e|0);I(a,0,d,0,c);I(b,0,d,c,e);return d}bk(0);var
aJ=am(1),aK=am(2),B=[0,function(a){var
b=bm(0);for(;;){if(b){var
c=b[2],d=b[1];try{an(d)}catch(f){}var
b=c;continue}return 0}}];function
T(a){return k(B[1],0)}ao(aN,T);function
U(a,b,c,d,e){if(0<=e)if(0<=b)if(!((a.getLen()-e|0)<b))if(0<=d)if(!((c.getLen()-e|0)<d))return I(a,b,c,d,e);return A(aO)}var
V=bu(0),o=bo(V/8|0,(1<<(V-10|0))-1|0)-1|0,Z=[0,0];function
_(a){Z[1]=[0,a,Z[1]];return 0}function
$(a,b){var
c=[0,[0,a,0]],d=b[1];if(d){var
e=d[1];b[1]=c;e[2]=c;return 0}b[1]=c;b[2]=c;return 0}var
E=[0,aR];function
aa(a){var
b=a[2];if(b){var
c=b[1],d=c[2],e=c[1];a[2]=d;if(0===d)a[1]=0;return e}throw[0,E]}function
F(a,b){a[13]=a[13]+b[3]|0;return $(b,a[27])}var
ab=1000000010;function
G(a,b){return w(a[17],b,0,b.getLen())}function
t(a){return k(a[19],0)}function
ac(a,b){return k(a[20],b)}function
j(a,b,c){t(a);a[11]=1;var
d=(a[6]-c|0)+b|0,e=a[8],f=bi(e,d)?e:d;a[10]=f;a[9]=a[6]-a[10]|0;return ac(a,a[10])}function
ad(a,b){return j(a,0,b)}function
m(a,b){a[9]=a[9]-b|0;return ac(a,b)}function
ae(a){try{for(;;){var
p=a[27][2];if(!p)throw[0,E];var
h=p[1][1],o=h[1],b=h[2],Q=o<0?1:0,ac=h[3],ae=Q?(a[13]-a[12]|0)<a[9]?1:0:Q,R=1-ae;if(R){aa(a[27]);var
g=0<=o?o:ab;if(typeof
b===J)switch(b){case
1:var
z=a[2];if(z)a[2]=z[2];break;case
2:var
A=a[3];if(A)a[3]=A[2];break;case
3:var
B=a[2];if(B)ad(a,B[1][2]);else
t(a);break;case
4:if(a[10]!==(a[6]-a[9]|0)){var
v=aa(a[27]),S=v[1];a[12]=a[12]-v[3]|0;a[9]=a[9]+S|0}break;case
5:var
i=a[5];if(i){var
T=i[2];G(a,k(a[24],i[1]));a[5]=T}break;default:var
w=a[3];if(w){var
x=w[1][1],y=function(a,b){if(b){var
c=b[1],d=b[2];return bj(a,c)?[0,a,b]:[0,c,y(a,d)]}return[0,a,0]};x[1]=y(a[6]-a[9]|0,x[1])}}else
switch(b[0]){case
1:var
c=b[2],e=b[1],D=a[2];if(D){var
F=D[1],d=F[2];switch(F[1]){case
1:j(a,c,d);break;case
2:j(a,c,d);break;case
3:if(a[9]<g)j(a,c,d);else
m(a,e);break;case
4:if(a[11])m(a,e);else
if(a[9]<g)j(a,c,d);else
if(((a[6]-d|0)+c|0)<a[10])j(a,c,d);else
m(a,e);break;case
5:m(a,e);break;default:m(a,e)}}break;case
2:var
l=a[6]-a[9]|0,H=a[3],V=b[2],W=b[1];if(H){var
I=H[1][1],L=I[1];if(L){var
Y=L[1];try{var
f=I[1];for(;;){if(!f)throw[0,C];var
K=f[1],X=f[2];if(!bd(K,l)){var
f=X;continue}var
M=K;break}}catch(f){f=ap(f);if(f[1]!==C)throw f;var
M=Y}var
n=M}else
var
n=l;var
N=n-l|0;if(0<=N)m(a,N+W|0);else
j(a,n+V|0,a[6])}break;case
3:var
O=b[2],Z=b[1];if(a[8]<(a[6]-a[9]|0)){var
q=a[2];if(q)var
r=q[1],s=r[2],u=r[1],af=a[9]<s?0===u?0:5<=u?1:(ad(a,s),1):0;else
t(a)}var
_=a[9]-Z|0,$=1===O?1:a[9]<g?O:5;a[2]=[0,[0,$,_],a[2]];break;case
4:a[3]=[0,b[1],a[3]];break;case
5:var
P=b[1];G(a,k(a[23],P));a[5]=[0,P,a[5]];break;default:var
U=b[1];a[9]=a[9]-g|0;G(a,U);a[11]=0}a[12]=ac+a[12]|0;continue}break}}catch(f){f=ap(f);if(f[1]===E)return 0;throw f}return R}function
u(a,b,c){return[0,a,b,c]}var
af=[0,[0,-1,u(-1,aS,0)],0];function
ag(a){a[1]=af;return 0}function
H(a,b){var
d=a[1];if(d){var
e=d[1],c=e[2],f=c[1],g=d[2],h=c[2];if(e[1]<a[12])return ag(a);if(typeof
h!==J)switch(h[0]){case
1:case
2:var
j=b?(c[1]=a[13]+f|0,a[1]=g,0):b;return j;case
3:var
i=1-b,k=i?(c[1]=a[13]+f|0,a[1]=g,0):i;return k}return 0}return 0}var
D=v(80);bb(D,0,80,32);function
aU(a){return s(aW,s(a,aV))}function
aX(a){return s(aZ,s(a,aY))}function
a0(a){return 0}function
a1(a){return 0}function
ah(a,b){function
f(a){return 0}var
d=[0,0,0];function
g(a){return 0}var
e=u(-1,a2,0);$(e,d);var
c=[0,[0,[0,1,e],af],0,0,0,0,78,10,68,78,0,1,1,1,1,aI,a3,a,b,g,f,0,0,aU,aX,a0,a1,d];c[19]=function(a){return w(c[17],aT,0,1)};c[20]=function(a){var
b=a;for(;;){var
d=0<b?1:0;if(d){if(80<b){w(c[17],D,0,80);var
b=b-80|0;continue}return w(c[17],D,0,b)}return d}};return c}function
ai(d){function
a(a){return an(d)}return ah(function(a,b,c){if(0<=b)if(0<=c)if(!((a.getLen()-c|0)<b))return bn(d,a,b,c);return A(aL)},a)}var
a5=au,W=1<=au?a5:1,X=o<W?o:W,Y=v(X),f=[0,Y,0,X,Y],b=ai(aJ);ai(aK);function
a4(a){return 0}ah(function(a,b,c){var
g=b<0?1:0;if(g)var
h=g;else
var
j=c<0?1:0,h=j||((a.getLen()-c|0)<b?1:0);if(h)A(aQ);var
i=f[2]+c|0;if(f[3]<i){var
d=[0,f[3]];for(;;){if(d[1]<(f[2]+c|0)){d[1]=2*d[1]|0;continue}if(o<d[1]){if(!((f[2]+c|0)<=o))throw[0,R,aP];d[1]=o}var
e=v(d[1]);U(f[1],0,e,0,f[2]);f[1]=e;f[3]=d[1];break}}U(a,b,f[1],f[2],c);f[2]=i;return 0},a4);var
aM=B[1];B[1]=function(a){var
i=0;for(;;){if(1<b[14]){if(1<b[14]){if(b[14]<b[15]){F(b,[0,0,1,0]);H(b,1);H(b,0)}b[14]=b[14]-1|0}continue}b[13]=ab;ae(b);if(i)t(b);b[12]=1;b[13]=1;var
c=b[27];c[1]=0;c[2]=0;ag(b);b[2]=0;b[3]=0;b[4]=0;b[5]=0;b[10]=0;b[14]=0;b[9]=b[6];b[14]=b[14]+1|0;var
g=3,h=0;if(b[14]<b[15]){var
e=u(-b[13]|0,[3,h,g],0);F(b,e);if(0)H(b,1);b[1]=[0,[0,b[13],e],b[1]]}else
if(b[14]===b[15]){var
f=b[16],d=f.getLen();F(b,u(d,[0,f],d));ae(b)}k(b[18],0);return k(aM,0)}};var
aj=i;true;false;var
ak=[0,a7],a6=aj.Array;ao(a8,[0,ak,{}][0+1]);_(function(a){return a[1]===ak?[0,new
q(a[2].toString())]:0});_(function(a){return a
instanceof
a6?0:[0,new
q(a.toString())]});var
al={};aj.MyModule=al;var
a9=bg(0),a_=Object,a$=this;al.hello=bh(function(a){return a9.log(a_.keys(a$))});T(0);return}(function(){return this}()));
